version: '3.7'
services:
  db:
    image: postgres:12.1
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    restart: always
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app/
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pg_data:
  .:
